---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terraform Lint
permissions: { contents: read }

on:
  push: {}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3

      - name: Run terraform fmt
        run: mise exec -- terraform fmt -recursive --check
